version: 0.2

env:
  variables:
    app_path: "app/with-smt-alm-sample"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo ${IMAGE_TAG}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ${app_path}/src/
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo "[{\"name\":\"${IMAGE_NAME}\",\"tag\":\"${IMAGE_TAG}\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\"}]" > ${CODEBUILD_SRC_DIR}/imagedefinitions.json
artifacts:
    files: imagedefinitions.json
    discard-paths: yes
